- name: Update Packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes

- name: Install packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present

- name: Disable SSH Password Authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Enable Passwordless Sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^#wheel"
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"

- name: Restart SSH daemon
  service:
    name: sshd
    state: restarted
  when:
    - sshd_config.changed
